name:                pi-calculus-and-logic
version:             0.1.0.0
github:              "/pi-calculus-and-logic"
license:             BSD3
author:              ""
maintainer:          ""
copyright:           "2018  Enecuum"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/ksenia portu/pi-calculus-and-logic#readme>

dependencies:
- base >= 4.7 && < 5
- stm
- mtl
- random
- primes
- fixed-vector
- arithmoi
- parsec
- hashable
- containers
# TypeCompose >= 0.9.14
# data-default-class
# loch-th

library:
  source-dirs: src

executables:
  pi-calculus-and-logic-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - pi-calculus-and-logic

tests:
  pi-calculus-and-logic-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - pi-calculus-and-logic
